// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/streaming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingService_UploadSong_FullMethodName  = "/streaming.StreamingService/UploadSong"
	StreamingService_GetSongList_FullMethodName = "/streaming.StreamingService/GetSongList"
	StreamingService_GetSongByID_FullMethodName = "/streaming.StreamingService/GetSongByID"
)

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	UploadSong(ctx context.Context, in *SongUploadRequest, opts ...grpc.CallOption) (*SongUploadResponse, error)
	GetSongList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SongListResponse, error)
	GetSongByID(ctx context.Context, in *SongIDRequest, opts ...grpc.CallOption) (*SongResponse, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) UploadSong(ctx context.Context, in *SongUploadRequest, opts ...grpc.CallOption) (*SongUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SongUploadResponse)
	err := c.cc.Invoke(ctx, StreamingService_UploadSong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) GetSongList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SongListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SongListResponse)
	err := c.cc.Invoke(ctx, StreamingService_GetSongList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingServiceClient) GetSongByID(ctx context.Context, in *SongIDRequest, opts ...grpc.CallOption) (*SongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SongResponse)
	err := c.cc.Invoke(ctx, StreamingService_GetSongByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility.
type StreamingServiceServer interface {
	UploadSong(context.Context, *SongUploadRequest) (*SongUploadResponse, error)
	GetSongList(context.Context, *Empty) (*SongListResponse, error)
	GetSongByID(context.Context, *SongIDRequest) (*SongResponse, error)
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServiceServer struct{}

func (UnimplementedStreamingServiceServer) UploadSong(context.Context, *SongUploadRequest) (*SongUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSong not implemented")
}
func (UnimplementedStreamingServiceServer) GetSongList(context.Context, *Empty) (*SongListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSongList not implemented")
}
func (UnimplementedStreamingServiceServer) GetSongByID(context.Context, *SongIDRequest) (*SongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSongByID not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}
func (UnimplementedStreamingServiceServer) testEmbeddedByValue()                          {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	// If the following call pancis, it indicates UnimplementedStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_UploadSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).UploadSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_UploadSong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).UploadSong(ctx, req.(*SongUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_GetSongList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).GetSongList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_GetSongList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).GetSongList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingService_GetSongByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingServiceServer).GetSongByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamingService_GetSongByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingServiceServer).GetSongByID(ctx, req.(*SongIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadSong",
			Handler:    _StreamingService_UploadSong_Handler,
		},
		{
			MethodName: "GetSongList",
			Handler:    _StreamingService_GetSongList_Handler,
		},
		{
			MethodName: "GetSongByID",
			Handler:    _StreamingService_GetSongByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/streaming.proto",
}
